-- ================= Vị trí bỏ trống khi nhân sự nghỉ việc + danh sách tỉnh theo khu vực kinh doanh =================
-- Lịch sử người phụ trách địa bàn: khi nghỉ việc / gỡ phân công, vị trí được ghi lại và để TRỐNG
-- (hiện "Trống từ … · trước: …") cho đến khi phân công người mới (closed = 1) hoặc quyết định không tuyển lại.
CREATE TABLE IF NOT EXISTS territory_history (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  territory_id INTEGER NOT NULL REFERENCES territories(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  role TEXT NOT NULL,
  industry TEXT,
  is_concurrent INTEGER NOT NULL DEFAULT 0,
  since TEXT,
  ended_at TEXT NOT NULL DEFAULT (date('now')),
  reason TEXT,                                -- resigned | removed
  closed INTEGER NOT NULL DEFAULT 0,          -- 1 = đã có người mới / không tuyển lại
  filled_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_territory_history_open ON territory_history(closed, territory_id);
CREATE INDEX IF NOT EXISTS idx_territory_history_user ON territory_history(user_id);

-- Mã khu vực theo danh sách của phòng Kinh doanh: Duyên Hải = DHD, Hà Nội = HNC
UPDATE territories SET code = 'DHD' WHERE level = 'area' AND code = 'DH';
UPDATE territories SET code = 'HNC' WHERE level = 'area' AND code = 'HN';
-- Khu vực trải 2 miền: Nam Hà Nội (Miền Bắc; Quảng Bình, Quảng Trị thuộc Miền Trung),
-- Nam Miền Trung (Miền Trung; Bình Phước, Đồng Nai thuộc Miền Nam) → thêm nhánh thứ hai dưới miền còn lại (ASM phụ trách kiêm nhiệm)
INSERT INTO territories(name, code, level, parent_id, sort) SELECT 'Nam Hà Nội (Miền Trung)', 'NHN', 'area', (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1), 20
  WHERE (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) IS NOT NULL AND (SELECT id FROM territories WHERE level = 'area' AND code = 'NHN' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NULL;
INSERT INTO territories(name, code, level, parent_id, sort) SELECT 'Nam Miền Trung (Miền Nam)', 'NMT', 'area', (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1), 20
  WHERE (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) IS NOT NULL AND (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NULL;

-- 63 tỉnh / thành phố (tên trước sáp nhập 2025): tỉnh đã có (kể cả tên viết khác) được chuyển về đúng khu vực,
-- giữ nguyên người phụ trách; chưa có thì thêm mới
UPDATE territories SET name = 'Hải Dương', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Hải Dương') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Hải Dương', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1), 1 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Hải Dương');
UPDATE territories SET name = 'Hải Phòng', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Hải Phòng') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Hải Phòng', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1), 2 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Hải Phòng');
UPDATE territories SET name = 'Bắc Giang', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Bắc Giang') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Bắc Giang', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1), 3 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Bắc Giang');
UPDATE territories SET name = 'Bắc Ninh', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Bắc Ninh') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Bắc Ninh', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1), 4 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Bắc Ninh');
UPDATE territories SET name = 'Hưng Yên', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Hưng Yên') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Hưng Yên', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1), 5 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Hưng Yên');
UPDATE territories SET name = 'Thái Bình', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Thái Bình') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Thái Bình', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1), 6 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Thái Bình');
UPDATE territories SET name = 'Hà Nam', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Hà Nam') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Hà Nam', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1), 7 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Hà Nam');
UPDATE territories SET name = 'Nam Định', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Nam Định') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Nam Định', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1), 8 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Nam Định');
UPDATE territories SET name = 'Ninh Bình', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Ninh Bình') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Ninh Bình', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1), 9 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Ninh Bình');
UPDATE territories SET name = 'Thanh Hóa', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Thanh Hóa', 'Thanh Hoá') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Thanh Hóa', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1), 10 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DHD' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Thanh Hóa');
UPDATE territories SET name = 'Cao Bằng', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Cao Bằng') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Cao Bằng', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1), 1 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Cao Bằng');
UPDATE territories SET name = 'Điện Biên', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Điện Biên') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Điện Biên', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1), 2 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Điện Biên');
UPDATE territories SET name = 'Lai Châu', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Lai Châu') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Lai Châu', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1), 3 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Lai Châu');
UPDATE territories SET name = 'Lạng Sơn', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Lạng Sơn') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Lạng Sơn', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1), 4 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Lạng Sơn');
UPDATE territories SET name = 'Lào Cai', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Lào Cai') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Lào Cai', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1), 5 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Lào Cai');
UPDATE territories SET name = 'Yên Bái', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Yên Bái') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Yên Bái', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1), 6 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Yên Bái');
UPDATE territories SET name = 'Hoà Bình', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Hoà Bình', 'Hòa Bình') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Hoà Bình', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1), 7 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Hoà Bình');
UPDATE territories SET name = 'Phú Thọ', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Phú Thọ') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Phú Thọ', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1), 8 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Phú Thọ');
UPDATE territories SET name = 'Vĩnh Phúc', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Vĩnh Phúc') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Vĩnh Phúc', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1), 9 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Vĩnh Phúc');
UPDATE territories SET name = 'Quảng Ninh', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Quảng Ninh') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Quảng Ninh', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1), 10 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Quảng Ninh');
UPDATE territories SET name = 'Sơn La', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Sơn La') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Sơn La', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1), 11 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Sơn La');
UPDATE territories SET name = 'Bắc Kạn', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Bắc Kạn') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Bắc Kạn', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1), 12 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Bắc Kạn');
UPDATE territories SET name = 'Thái Nguyên', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Thái Nguyên') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Thái Nguyên', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1), 13 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Thái Nguyên');
UPDATE territories SET name = 'Hà Giang', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Hà Giang') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Hà Giang', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1), 14 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Hà Giang');
UPDATE territories SET name = 'Tuyên Quang', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Tuyên Quang') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Tuyên Quang', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1), 15 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DTB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Tuyên Quang');
UPDATE territories SET name = 'Hà Nội', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'HNC' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Hà Nội') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'HNC' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Hà Nội', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'HNC' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1), 1 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'HNC' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Hà Nội');
UPDATE territories SET name = 'Hà Tĩnh', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'NHN' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Hà Tĩnh') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'NHN' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Hà Tĩnh', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'NHN' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1), 1 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'NHN' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Hà Tĩnh');
UPDATE territories SET name = 'Nghệ An', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'NHN' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Nghệ An') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'NHN' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Nghệ An', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'NHN' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1), 2 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'NHN' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Bắc' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Nghệ An');
UPDATE territories SET name = 'Cần Thơ', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Cần Thơ') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Cần Thơ', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1), 1 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Cần Thơ');
UPDATE territories SET name = 'Hậu Giang', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Hậu Giang') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Hậu Giang', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1), 2 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Hậu Giang');
UPDATE territories SET name = 'Sóc Trăng', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Sóc Trăng') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Sóc Trăng', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1), 3 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Sóc Trăng');
UPDATE territories SET name = 'An Giang', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('An Giang') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'An Giang', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1), 4 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'An Giang');
UPDATE territories SET name = 'Kiên Giang', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Kiên Giang') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Kiên Giang', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1), 5 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Kiên Giang');
UPDATE territories SET name = 'Bến Tre', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Bến Tre') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Bến Tre', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1), 6 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Bến Tre');
UPDATE territories SET name = 'Trà Vinh', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Trà Vinh') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Trà Vinh', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1), 7 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Trà Vinh');
UPDATE territories SET name = 'Vĩnh Long', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Vĩnh Long') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Vĩnh Long', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1), 8 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'BMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Vĩnh Long');
UPDATE territories SET name = 'Bình Dương', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DNB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Bình Dương') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DNB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Bình Dương', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DNB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1), 1 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DNB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Bình Dương');
UPDATE territories SET name = 'Bà Rịa - Vũng Tàu', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DNB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Bà Rịa - Vũng Tàu', 'Bà Rịa Vũng Tàu', 'Vũng Tàu') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DNB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Bà Rịa - Vũng Tàu', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DNB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1), 2 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DNB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Bà Rịa - Vũng Tàu');
UPDATE territories SET name = 'Hồ Chí Minh', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DNB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Hồ Chí Minh', 'TP. Hồ Chí Minh', 'TP Hồ Chí Minh', 'Thành phố Hồ Chí Minh') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DNB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Hồ Chí Minh', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DNB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1), 3 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DNB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Hồ Chí Minh');
UPDATE territories SET name = 'Tiền Giang', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DNB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Tiền Giang') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DNB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Tiền Giang', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DNB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1), 4 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DNB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Tiền Giang');
UPDATE territories SET name = 'Đồng Tháp', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DNB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Đồng Tháp') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DNB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Đồng Tháp', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DNB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1), 5 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DNB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Đồng Tháp');
UPDATE territories SET name = 'Tây Ninh', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DNB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Tây Ninh') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DNB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Tây Ninh', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DNB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1), 6 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DNB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Tây Ninh');
UPDATE territories SET name = 'Long An', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'DNB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Long An') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'DNB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Long An', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'DNB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1), 7 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'DNB' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Long An');
UPDATE territories SET name = 'Bạc Liêu', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'NMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Bạc Liêu') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'NMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Bạc Liêu', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'NMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1), 1 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'NMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Bạc Liêu');
UPDATE territories SET name = 'Cà Mau', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'NMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Cà Mau') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'NMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Cà Mau', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'NMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1), 2 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'NMK' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Cà Mau');
UPDATE territories SET name = 'Bình Phước', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Bình Phước') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Bình Phước', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1), 1 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Bình Phước');
UPDATE territories SET name = 'Đồng Nai', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Đồng Nai') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Đồng Nai', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1), 2 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Nam' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Đồng Nai');
UPDATE territories SET name = 'Đà Nẵng', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'BMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Đà Nẵng') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'BMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Đà Nẵng', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'BMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1), 1 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'BMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Đà Nẵng');
UPDATE territories SET name = 'Quảng Nam', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'BMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Quảng Nam') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'BMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Quảng Nam', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'BMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1), 2 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'BMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Quảng Nam');
UPDATE territories SET name = 'Huế', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'BMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Huế', 'Thừa Thiên Huế', 'Thừa Thiên - Huế') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'BMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Huế', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'BMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1), 3 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'BMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Huế');
UPDATE territories SET name = 'Bình Định', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'BMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Bình Định') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'BMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Bình Định', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'BMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1), 4 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'BMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Bình Định');
UPDATE territories SET name = 'Gia Lai', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'BMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Gia Lai') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'BMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Gia Lai', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'BMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1), 5 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'BMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Gia Lai');
UPDATE territories SET name = 'Quảng Ngãi', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'BMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Quảng Ngãi') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'BMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Quảng Ngãi', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'BMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1), 6 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'BMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Quảng Ngãi');
UPDATE territories SET name = 'Kon Tum', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'BMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Kon Tum') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'BMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Kon Tum', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'BMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1), 7 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'BMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Kon Tum');
UPDATE territories SET name = 'Quảng Bình', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'NHN' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Quảng Bình') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'NHN' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Quảng Bình', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'NHN' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1), 1 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'NHN' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Quảng Bình');
UPDATE territories SET name = 'Quảng Trị', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'NHN' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Quảng Trị') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'NHN' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Quảng Trị', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'NHN' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1), 2 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'NHN' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Quảng Trị');
UPDATE territories SET name = 'Phú Yên', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Phú Yên') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Phú Yên', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1), 1 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Phú Yên');
UPDATE territories SET name = 'Đắk Lắk', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Đắk Lắk', 'Đắc Lắk') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Đắk Lắk', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1), 2 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Đắk Lắk');
UPDATE territories SET name = 'Khánh Hòa', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Khánh Hòa', 'Khánh Hoà') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Khánh Hòa', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1), 3 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Khánh Hòa');
UPDATE territories SET name = 'Ninh Thuận', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Ninh Thuận') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Ninh Thuận', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1), 4 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Ninh Thuận');
UPDATE territories SET name = 'Bình Thuận', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Bình Thuận') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Bình Thuận', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1), 5 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Bình Thuận');
UPDATE territories SET name = 'Đắk Nông', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Đắk Nông') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Đắk Nông', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1), 6 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Đắk Nông');
UPDATE territories SET name = 'Lâm Đồng', parent_id = (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) WHERE level = 'province' AND name IN ('Lâm Đồng') AND (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL;
INSERT INTO territories(name, level, parent_id, sort) SELECT 'Lâm Đồng', 'province', (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1), 7 WHERE (SELECT id FROM territories WHERE level = 'area' AND code = 'NMT' AND parent_id = (SELECT id FROM territories WHERE level = 'region' AND name = 'Miền Trung' LIMIT 1) LIMIT 1) IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM territories WHERE level = 'province' AND name = 'Lâm Đồng');

-- TP. Hồ Chí Minh nay thuộc khu vực Đông Nam Bộ: bỏ khu vực "Hồ Chí Minh" mặc định nếu không còn tỉnh / người phụ trách
DELETE FROM territories WHERE level = 'area' AND code = 'HCM'
  AND NOT EXISTS (SELECT 1 FROM territories c WHERE c.parent_id = territories.id)
  AND NOT EXISTS (SELECT 1 FROM territory_members m WHERE m.territory_id = territories.id);
