/**
 * Câu nói truyền cảm hứng cho Trang chủ — mỗi ngày một câu (giống nhau cho mọi người trong ngày), luôn tích cực.
 * Giữ câu ngắn (≤ ~140 ký tự) để hiển thị gọn trên cả điện thoại.
 */
export const QUOTES = [
  ['Mỗi ngày là một cơ hội mới để làm tốt hơn hôm qua.', 'Khuyết danh'],
  ['Thành công là tổng của những nỗ lực nhỏ, lặp đi lặp lại mỗi ngày.', 'Robert Collier'],
  ['Cách tốt nhất để dự đoán tương lai là tạo ra nó.', 'Peter Drucker'],
  ['Hãy bắt đầu từ nơi bạn đứng, dùng những gì bạn có, làm những gì bạn có thể.', 'Arthur Ashe'],
  ['Không có việc gì khó, chỉ sợ lòng không bền.', 'Hồ Chí Minh'],
  ['Một mình chúng ta làm được ít, cùng nhau chúng ta làm được nhiều.', 'Helen Keller'],
  ['Chất lượng không phải là một hành động, đó là một thói quen.', 'Will Durant'],
  ['Hãy làm việc bạn yêu và yêu việc bạn làm.', 'Khuyết danh'],
  ['Điều quan trọng không phải là bạn đi chậm thế nào, miễn là bạn không dừng lại.', 'Khổng Tử'],
  ['Đi một ngày đàng, học một sàng khôn.', 'Tục ngữ Việt Nam'],
  ['Có công mài sắt, có ngày nên kim.', 'Tục ngữ Việt Nam'],
  ['Một cây làm chẳng nên non, ba cây chụm lại nên hòn núi cao.', 'Ca dao Việt Nam'],
  ['Thái độ tích cực biến mọi khó khăn thành cơ hội.', 'Khuyết danh'],
  ['Hành trình vạn dặm bắt đầu từ một bước chân.', 'Lão Tử'],
  ['Hãy là sự thay đổi mà bạn muốn thấy.', 'Mahatma Gandhi'],
  ['Mọi thứ đều có vẻ không thể cho đến khi nó được hoàn thành.', 'Nelson Mandela'],
  ['Tập trung vào giải pháp, không phải vấn đề.', 'Khuyết danh'],
  ['Hôm nay hãy làm điều mà tương lai bạn sẽ cảm ơn.', 'Khuyết danh'],
  ['Kiên nhẫn và bền bỉ luôn chiến thắng.', 'Khuyết danh'],
  ['Người thành công luôn tìm cách, người thất bại luôn tìm lý do.', 'Khuyết danh'],
  ['Mỗi chuyên gia đều từng là người mới bắt đầu.', 'Helen Hayes'],
  ['Làm việc chăm chỉ trong im lặng, để thành công lên tiếng.', 'Khuyết danh'],
  ['Hãy mỉm cười — năng lượng tích cực lan toả nhanh hơn bạn nghĩ.', 'Khuyết danh'],
  ['Đừng đếm ngày, hãy làm cho mỗi ngày đều đáng giá.', 'Muhammad Ali'],
  ['Khó khăn tạo nên sức mạnh, thử thách làm nên bản lĩnh.', 'Khuyết danh'],
  ['Học, học nữa, học mãi.', 'V. I. Lenin'],
  ['Tài năng thắng trận đấu, tinh thần đồng đội thắng giải vô địch.', 'Michael Jordan'],
  ['Việc hôm nay chớ để ngày mai.', 'Tục ngữ Việt Nam'],
  ['Nỗ lực hôm nay là thành quả của ngày mai.', 'Khuyết danh'],
  ['Một thái độ tốt dẫn đến một ngày tốt.', 'Khuyết danh'],
  ['Hãy biến mục tiêu lớn thành những bước nhỏ và bắt đầu ngay.', 'Khuyết danh'],
  ['Cơ hội không tự đến, chúng ta tạo ra nó.', 'Chris Grosser'],
  ['Hãy tin rằng bạn làm được, và bạn đã đi được nửa đường.', 'Theodore Roosevelt'],
  ['Thành công không phải đích đến, mà là cả một hành trình.', 'Arthur Ashe'],
  ['Sự khác biệt giữa bình thường và phi thường là một chút nỗ lực thêm.', 'Jimmy Johnson'],
  ['Làm tốt những việc nhỏ, việc lớn sẽ tự tìm đến.', 'Khuyết danh'],
  ['Mỗi sáng thức dậy, bạn có hai lựa chọn: tiếp tục mơ, hoặc đứng dậy thực hiện ước mơ.', 'Khuyết danh'],
  ['Khi cùng chung mục tiêu, mọi thử thách đều nhỏ lại.', 'Khuyết danh'],
  ['Hãy trân trọng những gì bạn có trong khi theo đuổi những gì bạn muốn.', 'Khuyết danh'],
  ['Không ngừng cải tiến — một phần trăm mỗi ngày là rất nhiều sau một năm.', 'Khuyết danh'],
  ['Cách để bắt đầu là ngừng nói và bắt tay vào làm.', 'Walt Disney'],
  ['Thất bại là cơ hội để bắt đầu lại một cách thông minh hơn.', 'Henry Ford'],
  ['Hãy làm hết sức, phần còn lại để thời gian trả lời.', 'Khuyết danh'],
  ['Niềm vui trong công việc tạo nên sự hoàn hảo trong kết quả.', 'Aristotle'],
  ['Người giỏi không phải người không bao giờ sai, mà là người biết sửa sai nhanh nhất.', 'Khuyết danh'],
  ['Biết ơn biến những gì ta có thành đủ đầy.', 'Khuyết danh'],
  ['Thời gian là tài sản quý nhất — hãy đầu tư nó thật khôn ngoan.', 'Khuyết danh'],
  ['Mọi thành tựu lớn đều bắt đầu từ quyết định thử.', 'Khuyết danh'],
  ['Uống nước nhớ nguồn.', 'Tục ngữ Việt Nam'],
  ['Chúng ta trở thành những gì chúng ta lặp lại mỗi ngày.', 'Will Durant'],
  ['Đoàn kết, đoàn kết, đại đoàn kết. Thành công, thành công, đại thành công.', 'Hồ Chí Minh'],
  ['Hãy lắng nghe để hiểu, không chỉ để trả lời.', 'Khuyết danh'],
  ['Tinh thần trách nhiệm là nền tảng của mọi sự tin tưởng.', 'Khuyết danh'],
  ['Sáng tạo là cho phép bản thân được thử và được sai.', 'Scott Adams'],
  ['Không có đường tắt đến nơi nào đáng đến.', 'Beverly Sills'],
  ['Một ngày làm việc hiệu quả bắt đầu bằng một việc quan trọng nhất.', 'Khuyết danh'],
  ['Điều bạn làm hôm nay có thể cải thiện mọi ngày mai của bạn.', 'Ralph Marston'],
  ['Hãy gieo hạt tốt mỗi ngày, mùa gặt sẽ đến.', 'Khuyết danh'],
  ['Tốc độ không quan trọng bằng phương hướng.', 'Khuyết danh'],
  ['Cho đi sự hỗ trợ, bạn sẽ nhận lại một đội ngũ vững mạnh.', 'Khuyết danh'],
  ['Sự chuẩn bị tốt là một nửa thành công.', 'Miguel de Cervantes'],
  ['Hãy tự hào về những tiến bộ nhỏ — chúng cộng dồn thành điều lớn.', 'Khuyết danh'],
  ['Khi bạn thay đổi cách nhìn, những điều bạn nhìn cũng thay đổi.', 'Wayne Dyer'],
  ['Thành công đến từ việc làm những điều bình thường một cách phi thường tốt.', 'Jim Rohn'],
  ['Kỷ luật là cầu nối giữa mục tiêu và thành tựu.', 'Jim Rohn'],
  ['Hãy làm việc thông minh, không chỉ chăm chỉ.', 'Khuyết danh'],
  ['Mỗi khách hàng hài lòng là lời quảng cáo tốt nhất.', 'Khuyết danh'],
  ['Hãy truyền cảm hứng bằng chính hành động của bạn.', 'Khuyết danh'],
  ['Lời khen chân thành là món quà miễn phí mà giá trị vô cùng.', 'Khuyết danh'],
  ['Đừng ngại bắt đầu lại — lần này bạn không bắt đầu từ con số 0, mà từ kinh nghiệm.', 'Khuyết danh'],
  ['Năng lượng tích cực là nhiên liệu tốt nhất cho một ngày làm việc.', 'Khuyết danh'],
  ['Hãy mơ lớn, bắt đầu nhỏ, hành động ngay.', 'Robin Sharma'],
  ['Người lạc quan nhìn thấy cơ hội trong mọi khó khăn.', 'Winston Churchill'],
  ['Mục tiêu rõ ràng giúp mỗi bước đi đều có ý nghĩa.', 'Khuyết danh'],
  ['Thành công của tập thể là niềm vui của mỗi cá nhân.', 'Khuyết danh'],
  ['Chỉ cần tiến lên, dù là từng bước nhỏ.', 'Khuyết danh'],
  ['Hãy tử tế — mỗi người bạn gặp đều đang cố gắng hết mình.', 'Khuyết danh'],
  ['Chăm chỉ vượt qua tài năng khi tài năng không chăm chỉ.', 'Tim Notke'],
  ['Hôm nay là ngày tuyệt vời để hoàn thành một điều ý nghĩa.', 'Khuyết danh'],
  ['Học hỏi từ hôm qua, sống cho hôm nay, hy vọng cho ngày mai.', 'Albert Einstein'],
  ['Sự tận tâm biến công việc bình thường thành dấu ấn riêng.', 'Khuyết danh'],
  ['Cuộc sống bắt đầu ở nơi vùng an toàn kết thúc.', 'Neale Donald Walsch'],
  ['Mỗi vấn đề đều là một món quà — thiếu vấn đề, ta không trưởng thành.', 'Tony Robbins'],
  ['Giao tiếp tốt là cầu nối giữa sự bối rối và sự rõ ràng.', 'Nat Turner'],
  ['Ăn quả nhớ kẻ trồng cây.', 'Tục ngữ Việt Nam'],
  ['Hãy làm cho người khác cảm thấy họ quan trọng — vì họ thực sự quan trọng.', 'Khuyết danh'],
  ['Sự kiên trì là chìa khoá mở mọi cánh cửa.', 'Khuyết danh'],
  ['Mỗi ngày một việc tốt, mỗi tháng một bước tiến.', 'Khuyết danh'],
  ['Không có gì là không thể với một người luôn cố gắng.', 'Khuyết danh'],
  ['Hãy biến “tôi sẽ thử” thành “tôi sẽ làm”.', 'Khuyết danh'],
  ['Một đội ngũ tin tưởng nhau có thể làm nên điều kỳ diệu.', 'Khuyết danh'],
  ['Hãy để công việc hôm nay là niềm tự hào của ngày mai.', 'Khuyết danh'],
  ['Thành công lớn nhất là vượt qua chính mình của ngày hôm qua.', 'Khuyết danh'],
  ['Giữ lửa đam mê, mọi con đường đều sẽ sáng.', 'Khuyết danh'],
  ['Bình tĩnh, tập trung và làm từng việc một.', 'Khuyết danh'],
  ['Sự đơn giản là đỉnh cao của sự tinh tế.', 'Leonardo da Vinci'],
  ['Đừng chờ cơ hội, hãy chuẩn bị để sẵn sàng khi nó đến.', 'Khuyết danh'],
  ['Ngày mới, năng lượng mới, thành công mới!', 'Khuyết danh'],
];

/** Chỉ số câu nói của một ngày: băm chuỗi ngày để các ngày liền nhau không ra câu liền nhau. */
export function quoteIndexFor(date = new Date()) {
  const key = `${date.getFullYear()}-${date.getMonth() + 1}-${date.getDate()}`;
  let h = 2166136261;
  for (let i = 0; i < key.length; i++) { h ^= key.charCodeAt(i); h = Math.imul(h, 16777619); }
  return (h >>> 0) % QUOTES.length;
}
